version: '1.0.0.-alpha-{build}'

init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER
configuration:
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- appveyor-retry npm install -g bower
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\PayFast" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "samples\PayFast.Web.Core" -c %CONFIGURATION% --framework netcoreapp1.0 --version-suffix %LABEL%
after_build:
- dotnet pack "src\PayFast" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o .\artifacts
- dotnet publish "samples\PayFast.Web.Core" -c %CONFIGURATION% --no-build --framework netcoreapp1.0 -o %appveyor_build_folder%\publish
test_script:
- dotnet test "test\PayFast.UnitTests" -c %CONFIGURATION%
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\publish
  name: PayFast.Web.Core
  type: WebDeployPackage
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/payfast/api/v2/package
  api_key:
    secure: kVGrfaSlHgz+m+0UiUI3Y7AcEk2FnjQzBu1h/y82hf/hRyPIVE0tgqhvb0RAZCBL
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 1afzvhhfr/tnKB9eqIj5MvLUBJq48BPazJGRLwkkfFfIPs06DL9RdAXfNli+bXhs
  skip_symbols: true
  on:
    branch: master
    # Only publish if the trigger was a Git tag
    # git tag v1.0.0-alpha
    # git push origin --tags
    appveyor_repo_tag: true
- provider: WebDeploy 
  server: https://payfast-demo.scm.azurewebsites.net:443/msdeploy.axd?site=payfast-demo 
  website: payfast-demo 
  username: 
    secure: UtwWSnKfFRQc7x3CjXHrnA==
  password: 
    secure: C6Rs8RqbFe5cl2hYSlC8kQ==
  artifact: PayFast.Web.Core
  aspnet_core: true 
  aspnet_core_force_restart: false 
  on: 
    branch: master